"""Add task list model

Revision ID: 3f0a4ec8962b
Revises: b85b12686413
Create Date: 2021-05-05 13:01:03.673413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0a4ec8962b'
down_revision = 'b85b12686413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TaskList',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TaskList')
    # ### end Alembic commands ###
