"""Add task list model[1]

Revision ID: 52b0069dc8cc
Revises: 3f0a4ec8962b
Create Date: 2021-05-05 13:05:19.000685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b0069dc8cc'
down_revision = '3f0a4ec8962b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Task', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Task', 'TaskList', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Task', type_='foreignkey')
    op.drop_column('Task', 'list_id')
    # ### end Alembic commands ###
