"""Add task list model[2]

Revision ID: 7f8833618845
Revises: 52b0069dc8cc
Create Date: 2021-05-05 14:54:24.421768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8833618845'
down_revision = '52b0069dc8cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
