"""empty message

Revision ID: b85b12686413
Revises: 73b4fa10ebfd
Create Date: 2021-05-04 15:28:22.991802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85b12686413'
down_revision = '73b4fa10ebfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
