"""Added cascade delete

Revision ID: f490550aca5a
Revises: 7f8833618845
Create Date: 2021-05-06 11:02:26.766577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f490550aca5a'
down_revision = '7f8833618845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Task_list_id_fkey', 'Task', type_='foreignkey')
    op.create_foreign_key(None, 'Task', 'TaskList', ['list_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Task', type_='foreignkey')
    op.create_foreign_key('Task_list_id_fkey', 'Task', 'TaskList', ['list_id'], ['id'])
    # ### end Alembic commands ###
